// Mocks generated by Mockito 5.4.6 from annotations
// in tokyo_flutter_hackathon_2025/test/features/manual_editing/domain/services/manual_edit_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:tokyo_flutter_hackathon_2025/core/utils/result.dart' as _i4;
import 'package:tokyo_flutter_hackathon_2025/features/manual_generation/domain/entities/manual.dart'
    as _i5;
import 'package:tokyo_flutter_hackathon_2025/features/manual_generation/domain/entities/manual_step.dart'
    as _i7;
import 'package:tokyo_flutter_hackathon_2025/features/manual_generation/domain/repositories/manual_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ManualRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockManualRepository extends _i1.Mock implements _i2.ManualRepository {
  MockManualRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<void>> saveManual(_i5.Manual? manual) =>
      (super.noSuchMethod(
            Invocation.method(#saveManual, [manual]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveManual, [manual]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.Manual?>> getManual(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getManual, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Manual?>>.value(
              _i6.dummyValue<_i4.Result<_i5.Manual?>>(
                this,
                Invocation.method(#getManual, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Manual?>>);

  @override
  _i3.Future<_i4.Result<void>> updateManual(_i5.Manual? manual) =>
      (super.noSuchMethod(
            Invocation.method(#updateManual, [manual]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateManual, [manual]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteManual(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteManual, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteManual, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Manual>>> getAllManuals() =>
      (super.noSuchMethod(
            Invocation.method(#getAllManuals, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Manual>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Manual>>>(
                this,
                Invocation.method(#getAllManuals, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Manual>>>);

  @override
  _i3.Future<_i4.Result<void>> saveManualStep(
    String? manualId,
    _i7.ManualStep? step,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveManualStep, [manualId, step]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#saveManualStep, [manualId, step]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> updateManualStep(
    String? manualId,
    _i7.ManualStep? step,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateManualStep, [manualId, step]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateManualStep, [manualId, step]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteManualStep(
    String? manualId,
    String? stepId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteManualStep, [manualId, stepId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteManualStep, [manualId, stepId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i7.ManualStep>>> getManualSteps(
    String? manualId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getManualSteps, [manualId]),
            returnValue: _i3.Future<_i4.Result<List<_i7.ManualStep>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.ManualStep>>>(
                this,
                Invocation.method(#getManualSteps, [manualId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.ManualStep>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Manual>>> searchManuals(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchManuals, [query]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Manual>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Manual>>>(
                this,
                Invocation.method(#searchManuals, [query]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Manual>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Manual>>> getManualsByStatus(
    _i5.ManualStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getManualsByStatus, [status]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Manual>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Manual>>>(
                this,
                Invocation.method(#getManualsByStatus, [status]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Manual>>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> exportManualAsJson(
    String? manualId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportManualAsJson, [manualId]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#exportManualAsJson, [manualId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Result<_i5.Manual>> importManualFromJson(
    Map<String, dynamic>? json,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importManualFromJson, [json]),
            returnValue: _i3.Future<_i4.Result<_i5.Manual>>.value(
              _i6.dummyValue<_i4.Result<_i5.Manual>>(
                this,
                Invocation.method(#importManualFromJson, [json]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Manual>>);
}
